version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest

    working_directory: ~/fraction

    steps:
      - checkout
      - run: rustc -vV
      - run: cargo -vV
      - run: cargo test --verbose --all-features
